runtime: nodejs20
env: standard

instance_class: F1

env_variables:
  NODE_ENV: "production"
  PORT: "8080"
  # Only keeping essential environment variables

handlers:
- url: /.*
  script: auto
  secure: always

automatic_scaling:
  min_instances: 1
  max_instances: 3
  min_idle_instances: 1

entrypoint: node app.js
